export type InvoiceStatus = 'Draft' | 'Unpaid' | 'Cancelled' | 'Paid';
export enum ModelNameEnum {
  Account = 'Account',
  AccountingLedgerEntry = 'AccountingLedgerEntry',
  AccountingSettings = 'AccountingSettings',
  Address = 'Address',
  Color = 'Color',
  CompanySettings = 'CompanySettings',
  Currency = 'Currency',
  GetStarted = 'GetStarted',
  Item = 'Item',
  JournalEntry = 'JournalEntry',
  JournalEntryAccount = 'JournalEntryAccount',
  NumberSeries = 'NumberSeries',
  Party = 'Party',
  Payment = 'Payment',
  PaymentFor = 'PaymentFor',
  PrintSettings = 'PrintSettings',
  PurchaseInvoice = 'PurchaseInvoice',
  PurchaseInvoiceItem = 'PurchaseInvoiceItem',
  SalesInvoice = 'SalesInvoice',
  SalesInvoiceItem = 'SalesInvoiceItem',
  SalesInvoiceSettings = 'SalesInvoiceSettings',
  SetupWizard = 'SetupWizard',
  Tax = 'Tax',
  TaxDetail = 'TaxDetail',
  TaxSummary = 'TaxSummary',
  PatchRun = 'PatchRun',
  SingleValue = 'SingleValue',
  SystemSettings = 'SystemSettings',
}

export type ModelName = keyof typeof ModelNameEnum